import { useEffect, useMemo, useState } from 'react'
import { addCommercialProgram, alterCommercialProgram, availableComponents, buildFactory, buyMaterialsCommercial, canResearch, components, designStats, initialGame, issueEquity, issueLoan, regions, research, researches, researchStatus, advanceChannel, commercial, unitEconomics, type Game, type Segment } from './game'
import './styles.css'

const cash=(n:number)=>`$${n.toFixed(1)}k`
const segments:Segment[]=['Value homes','Premium homes','Broadcasters','Industry','Government','Business']
function Metric({name,value,alert}:{name:string;value:string;alert?:boolean}){return <div className={alert?'metric alert':'metric'}><span>{name}</span><b>{value}</b></div>}
export function App(){
 const [game,setGame]=useState<Game>(()=>{try{const saved=JSON.parse(localStorage.getItem('radiant-industries-deep')||'');return saved?.version===2?saved:initialGame()}catch{return initialGame()}})
 const [tab,setTab]=useState<'desk'|'map'|'design'|'operations'|'finance'|'research'>('desk')
 const [name,setName]=useState('Radiant Home Receiver'),[segment,setSegment]=useState<Segment>('Value homes'),[price,setPrice]=useState(85),[discount,setDiscount]=useState(35),[parts,setParts]=useState<string[]>(['tube','am','utility'])
 useEffect(()=>localStorage.setItem('radiant-industries-deep',JSON.stringify(game)),[game])
 const apply=(fn:(g:Game)=>Game)=>setGame(fn)
 const stats=useMemo(()=>designStats(parts),[parts]); const available=availableComponents(game)
 const toggle=(id:string,group:string)=>setParts(current=>current.includes(id)?current.filter(x=>x!==id):[...current.filter(x=>components.find(c=>c.id===x)?.group!==group),id])
 return <main className="tycoon">
  <header className="masthead"><div className="brand"><span className="mark">R</span><div><h1>RADIANT <i>INDUSTRIES</i></h1><p>NATIONAL ELECTRONICS COMBINE · {game.year} Q{game.quarter}</p></div></div><div className="board-chip">BOARD CONFIDENCE <b>{game.board}</b></div><button className="advance" onClick={()=>apply(advanceChannel)}>Close Quarter <span>→</span></button></header>
  <section className="ticker"><span>EXECUTIVE WIRE</span><p>{game.action}</p><strong>{game.objectives[0]}</strong></section>
  <nav>{(['desk','map','design','operations','finance','research'] as const).map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'active':''}>{x}</button>)}</nav>
  <section className="metrics"><Metric name="Treasury" value={cash(game.cash)} alert={game.cash<30}/><Metric name="Quarterly profit" value={cash(game.ledger.profit)} alert={game.ledger.profit<0}/><Metric name="Debt" value={cash(game.debt)} /><Metric name="Market share" value={`${game.marketShare}%`} /></section>
  {tab==='desk'&&<div className="desk-grid"><section className="panel chairman"><p className="eyebrow">CHAIRMAN'S DESK</p><h2>An industry is<br/><i>an argument.</i></h2><p>Use capital to turn engineering into a durable national business. Products only matter when they earn their keep.</p><div className="board-objectives"><b>BOARD MANDATE</b>{game.objectives.map(x=><span key={x}>◆ {x}</span>)}</div></section><section className="panel report"><p className="eyebrow">LAST QUARTER · P&L</p>{[['Revenue',game.ledger.revenue],['Cost of goods',-game.ledger.cogs],['Payroll',-game.ledger.payroll],['Marketing',-game.ledger.marketing],['Interest',-game.ledger.interest],['Net income',game.ledger.profit]].map(([n,v])=><div key={String(n)}><span>{n}</span><b className={Number(v)<0?'negative':''}>{cash(Number(v))}</b></div>)}</section><section className="panel dispatch"><p className="eyebrow">BOARD DISPATCHES</p>{game.notices.slice(0,4).map((n,i)=><article key={i} className={n.tone}><b>{n.title}</b><p>{n.body}</p></article>)}</section><section className="panel factories"><p className="eyebrow">NATIONAL FOOTPRINT</p>{game.factories.map(f=><div key={f.id}><b>{f.name}</b><span>{f.region} · {f.capacity} units · {f.raw} raw lots</span></div>)}</section></div>}
  {tab==='map'&&<section className="panel page"><div className="section-title"><div><p className="eyebrow">UNITED STATES COMMERCIAL MAP</p><h2>Sell where the <i>people are.</i></h2></div><p className="muted">Regional income, retail reach, labor, and freight drive opportunity.</p></div><div className="region-map">{regions.map((r,i)=>{const has=game.factories.some(f=>f.region===r.id);return <article className={has?'regional owned':'regional'} key={r.id} style={{'--i':i} as React.CSSProperties}><span>{has?'WORKS':'MARKET'}</span><h3>{r.id}</h3><p>Demand {Math.round(r.demand*100)} · Retail {Math.round(r.retail*100)}</p><small>Labor {Math.round(r.labor*100)} · Freight {Math.round(r.freight*100)}</small>{!has&&<button disabled={game.cash<85} onClick={()=>apply(g=>buildFactory(g,r.id))}>Build works · $85k</button>}</article>})}</div></section>}
  {tab==='design'&&<section className="panel page"><div className="section-title"><div><p className="eyebrow">ENGINEERING BENCH</p><h2>Design the <i>margin.</i></h2></div><p className="muted">MSRP drives demand; dealer terms buy shelf space.</p></div><div className="design-grid"><section className="program-form"><label>Program name<input value={name} onChange={e=>setName(e.target.value)} /></label><label>Customer segment<select value={segment} onChange={e=>setSegment(e.target.value as Segment)}>{segments.map(x=><option key={x}>{x}</option>)}</select></label><label>MSRP<input type="number" min="20" value={price} onChange={e=>setPrice(Number(e.target.value))}/></label><label>Dealer discount (%)<input type="number" min="20" max="45" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label><div className="design-stats"><span>Bill of materials <b>${stats.cost}</b></span><span>Wholesale net <b>${(price*(1-discount/100)).toFixed(0)}</b></span><span>Est. unit margin <b>${(price*(1-discount/100)-stats.cost-12-(100-stats.reliability)*.11).toFixed(0)}</b></span><span>Reliability <b>{stats.reliability}%</b></span></div><button className="primary" disabled={game.cash<30} onClick={()=>apply(g=>addCommercialProgram(g,name,segment,price,discount/100,parts))}>Approve program · $30k tooling</button></section><section className="component-rack">{(['platform','signal','finish','feature'] as const).map(group=><div className="component-group" key={group}><h3>{group}</h3>{available.filter(c=>c.group===group).map(c=><button key={c.id} className={parts.includes(c.id)?'selected':''} onClick={()=>toggle(c.id,c.group)}><b>{c.name}</b><small>${c.cost} BOM · +{c.appeal} appeal · {c.reliability}% reliable</small></button>)}</div>)}</section></div></section>}
  {tab==='operations'&&<section className="panel page"><div className="section-title"><div><p className="eyebrow">WORKS & INVENTORY</p><h2>Make it <i>well.</i></h2></div><p className="muted">Materials are capital until a finished good sells.</p></div><div className="operations-grid"><section>{game.factories.map(f=><article className="factory-card" key={f.id}><h3>{f.name}</h3><p>{f.region} · {f.workers} workers · {f.capacity} quarterly capacity</p><div><span>Raw component lots <b>{f.raw}</b></span><button onClick={()=>apply(g=>buyMaterialsCommercial(g,f.id))}>Order 180 lots · market price</button></div></article>)}</section><section className="programs"><p className="eyebrow">PRODUCT PROGRAMS</p>{game.programs.length?game.programs.map(p=>{const cp=commercial(p),u=unitEconomics(p);return <article key={p.id}><div><b>{p.name}</b><small>{p.segment} · {p.inventory} finished · {p.unitsSold} sold · ${u.margin.toFixed(0)} est. contribution/unit</small></div><label>MSRP <input type="number" value={cp.msrp} onChange={e=>apply(g=>alterCommercialProgram(g,p.id,'msrp',Number(e.target.value)))}/></label><label>Dealer % <input type="number" min="20" max="45" value={Math.round(cp.dealerDiscount*100)} onChange={e=>apply(g=>alterCommercialProgram(g,p.id,'dealerDiscount',Number(e.target.value)/100))}/></label><label>Marketing <input type="number" value={p.marketing} onChange={e=>apply(g=>alterCommercialProgram(g,p.id,'marketing',Number(e.target.value)))}/></label><strong>{cash(p.revenue)}</strong></article>}):<div className="empty">No program in production.<br/>Commission one from the engineering bench.</div>}</section></div></section>}
  {tab==='finance'&&<section className="panel page"><div className="section-title"><div><p className="eyebrow">TREASURER'S OFFICE</p><h2>Capital has a <i>cost.</i></h2></div><p className="muted">Cash flow pays for factories; profit alone does not.</p></div><div className="finance-grid"><section className="ledger"><h3>Cash flow</h3>{[['Operating cash flow',game.ledger.cashFlow],['Revenue',game.ledger.revenue],['COGS',-game.ledger.cogs],['Freight',-game.ledger.freight],['Payroll',-game.ledger.payroll],['Overhead',-game.ledger.overhead],['Tax',-game.ledger.tax]].map(([n,v])=><div key={String(n)}><span>{n}</span><b className={Number(v)<0?'negative':''}>{cash(Number(v))}</b></div>)}</section><section className="capital"><h3>Capital market</h3><p>Debt funds expansion but requires quarterly interest. Equity funds growth without repayments but reduces board confidence.</p><button onClick={()=>apply(issueLoan)}>Issue bank loan <small>+$100k · 2.5% / qtr</small></button><button onClick={()=>apply(issueEquity)}>Raise equity <small>+$120k · board −5</small></button><div className="debt-list">{game.loans.length?game.loans.map(l=><span key={l.id}>Bank note: {cash(l.principal)} · {l.rate*100}% quarterly</span>):'No outstanding notes.'}</div></section></div></section>}
  {tab==='research'&&<section className="panel page"><div className="section-title"><div><p className="eyebrow">CORPORATE RESEARCH BUREAU</p><h2>Patent the <i>future.</i></h2></div><div className="rp">AVAILABLE <b>{game.research} RP</b></div></div><div className="research-grid">{researches.map(r=>{const status=researchStatus(game,r);return <button className={`research-card ${game.techs.includes(r.id)?'done':''} ${canResearch(game,r)?'available':''}`} key={r.id} disabled={!canResearch(game,r)} onClick={()=>apply(g=>research(g,r.id))}><span>{game.techs.includes(r.id)?'✓':r.cost}</span><em>{r.year}</em><b>{r.name}</b><p>{r.description}</p><small>{r.unlocks.length?`Unlocks: ${r.unlocks.join(', ')}`:status}</small><i>{game.techs.includes(r.id)?'Completed':status}</i></button>})}</div></section>}
 </main>
}
