import { useEffect, useMemo, useState } from 'react'
import { advance, canResearch, catalog, initialGame, invest, launch, research, techs, type Category, type Game } from './game'

const branches: Category[]=['Wireless','Television','Components','Professional']
const money=(n:number)=>`$${n.toFixed(1)}k`
function Stat({label,value,delta}:{label:string,value:string,delta?:string}){return <div className="stat"><span>{label}</span><b>{value}</b>{delta&&<em>{delta}</em>}</div>}
export function App(){
 const [game,setGame]=useState<Game>(()=>{try{return JSON.parse(localStorage.getItem('radiant-industries')||'') as Game}catch{return initialGame()}})
 const [tab,setTab]=useState<'overview'|'research'|'products'|'ledger'>('overview')
 useEffect(()=>localStorage.setItem('radiant-industries',JSON.stringify(game)),[game])
 const unlocked=useMemo(()=>techs.filter(t=>game.techs.includes(t.id)),[game.techs])
 const apply=(fn:(g:Game)=>Game)=>setGame(fn)
 return <main>
  <header className="masthead"><div className="brand"><span className="mark">R</span><div><h1>RADIANT <i>INDUSTRIES</i></h1><p>AN ELECTRIC AMERICAN FUTURE</p></div></div><div className="date"><b>{game.year}</b><span>QUARTER {game.quarter}</span></div><button className="advance" onClick={()=>apply(advance)}>Close Quarter <span>→</span></button></header>
  <section className="ticker"><span>BOARD WIRE</span><p>{game.action}</p><strong>MARKET SHARE {game.marketShare}%</strong></section>
  <nav>{(['overview','research','products','ledger'] as const).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>
  <section className="metrics"><Stat label="Treasury" value={money(game.cash)} delta={game.lastProfit?`${game.lastProfit>=0?'+':''}${money(game.lastProfit)} last qtr`:undefined}/><Stat label="Research Points" value={`${game.research} RP`} /><Stat label="Factory Output" value={`${game.capacity} units`} /><Stat label="Brand Prestige" value={`${game.prestige}/100`} /></section>
  {tab==='overview'&&<div className="grid overview">
   <section className="hero panel"><p className="eyebrow">THE CHAIRMAN'S DESK</p><h2>Make the future<br/><i>commercial.</i></h2><p className="lead">Every new invention is a wager. Decide where Radiant puts its people, capital, and confidence.</p><div className="actions"><button onClick={()=>apply(g=>invest(g,'research'))} disabled={game.cash<20}>Fund laboratory <small>$20k · +2 RP</small></button><button onClick={()=>apply(g=>invest(g,'factory'))} disabled={game.cash<35}>Expand works <small>$35k · +55 units</small></button><button onClick={()=>apply(g=>invest(g,'distribution'))} disabled={game.cash<28}>Open territory <small>$28k · +1 region</small></button></div></section>
   <section className="chart panel"><p className="eyebrow">TREASURY · 12 QUARTERS</p><div className="bars">{game.history.map((v,i)=>{const min=Math.min(...game.history);const max=Math.max(...game.history);const h=28+((v-min)/(max-min||1))*72;return <span key={i} style={{height:`${h}%`}} title={money(v)} />})}</div><div className="chartfoot"><span>FOUNDING</span><b>{money(game.cash)}</b><span>NOW</span></div></section>
   <section className="briefing panel"><p className="eyebrow">LATEST DISPATCHES</p>{game.notices.slice(0,3).map((n,i)=><article key={i} className={n.tone}><h3>{n.title}</h3><p>{n.body}</p></article>)}</section>
   <section className="portfolio panel"><p className="eyebrow">PRODUCT PORTFOLIO</p>{game.products.length?<div className="product-list">{game.products.map(p=><div key={p.id}><span className="dot"/><div><b>{p.name}</b><small>{p.units.toLocaleString()} units last quarter</small></div><strong>{money(p.revenue)}</strong></div>)}</div>:<div className="empty">No products on sale.<br/>Fund research, then turn an invention into a product.</div>}</section>
  </div>}
  {tab==='research'&&<section className="panel research"><div className="section-title"><div><p className="eyebrow">CORPORATE RESEARCH BUREAU</p><h2>The patent <i>frontier.</i></h2></div><div className="rp">AVAILABLE <b>{game.research} RP</b></div></div>{branches.map(branch=><div className="branch" key={branch}><h3>{branch}</h3><div className="techrow">{techs.filter(t=>t.branch===branch).map(t=>{const got=game.techs.includes(t.id),available=canResearch(game,t);return <button className={`tech ${got?'done':''} ${available?'available':''}`} key={t.id} disabled={!available} onClick={()=>apply(g=>research(g,t.id))}><span>{got?'✓':t.cost}</span><b>{t.name}</b><small>{t.description}</small>{!got&&t.requires&&!game.techs.includes(t.requires)&&<i>Requires prior breakthrough</i>}</button>})}</div></div>)}</section>}
  {tab==='products'&&<section className="panel products"><div className="section-title"><div><p className="eyebrow">MARKET OFFICE</p><h2>Things people <i>choose.</i></h2></div><p className="muted">Launch cost: $18k · Manufacturing capacity is shared</p></div><div className="catalog">{unlocked.map(t=>{const entry=catalog[t.id], exists=game.products.some(p=>p.tech===t.id);return entry&&<article key={t.id} className={exists?'launched':''}><div className="poster"><span>{entry.category}</span><b>{entry.name.split(' ').slice(-1)}</b></div><h3>{entry.name}</h3><p>{t.description}</p><div><strong>${entry.price}</strong><button disabled={exists||game.cash<18} onClick={()=>apply(g=>launch(g,t.id))}>{exists?'In market':'Launch product'}</button></div></article>})}{!unlocked.length&&<div className="empty wide">Your laboratories have not released a production-ready invention.</div>}</div></section>}
  {tab==='ledger'&&<section className="panel ledger"><p className="eyebrow">AUDITORS' RECORD</p><h2>The company at a <i>glance.</i></h2><div className="ledgergrid"><div><span>Cash on hand</span><b>{money(game.cash)}</b></div><div><span>Debt</span><b>{money(game.debt)}</b></div><div><span>Distribution regions</span><b>{game.distribution}</b></div><div><span>Products in market</span><b>{game.products.length}</b></div><div><span>Patents held</span><b>{game.techs.length}</b></div><div><span>Last quarterly profit</span><b className={game.lastProfit<0?'loss':''}>{money(game.lastProfit)}</b></div></div><button className="newgame" onClick={()=>{if(confirm('Start a new company? Your saved campaign will be replaced.')) setGame(initialGame())}}>Dissolve & start anew</button></section>}
 </main>
}
