import { useEffect, useMemo, useState } from 'react'
import { addCommercialProgram, alterCommercialProgram, availableComponents, canResearch, components, designStats, initialGame, issueEquity, issueLoan, regions, research, researches, researchEffectText, researchStatus, advanceCompetitive as advanceChannel, fundStandard, rivals, activeEvents, unitEconomics, type Game, type ResearchBranch, type Segment } from './game'
import './styles.css'
import './notifications.css'

const cash=(n:number)=>`$${n.toFixed(1)}k`
const segments:Segment[]=['Value homes','Premium homes','Broadcasters','Industry','Government','Business']
type Tab='desk'|'markets'|'design'|'portfolio'|'finance'|'research'
function Metric({name,value,alert}:{name:string;value:string;alert?:boolean}){return <div className={alert?'metric alert':'metric'}><span>{name}</span><b>{value}</b></div>}
export function App(){
 const [game,setGame]=useState<Game>(()=>{try{const saved=JSON.parse(localStorage.getItem('radiant-industries-portfolio')||'');return saved?.version===4?saved:initialGame()}catch{return initialGame()}})
 const [tab,setTab]=useState<Tab>('desk'),[branch,setBranch]=useState<'All'|ResearchBranch>('All')
 const [name,setName]=useState('Radiant Home Receiver'),[segment,setSegment]=useState<Segment>('Value homes'),[price,setPrice]=useState(145),[discount,setDiscount]=useState(35),[parts,setParts]=useState<string[]>(['tube','am','utility'])
 useEffect(()=>localStorage.setItem('radiant-industries-portfolio',JSON.stringify(game)),[game])
 const apply=(fn:(g:Game)=>Game)=>setGame(fn)
 const stats=useMemo(()=>designStats(parts),[parts]);const available=availableComponents(game);const breakEven=Math.ceil((stats.cost+18+(100-stats.reliability)*.11)/(1-discount/100));const receivables=game.receivables.reduce((n,i)=>n+i.amount,0)
 const toggle=(id:string,group:string)=>setParts(current=>current.includes(id)?current.filter(x=>x!==id):[...current.filter(x=>components.find(c=>c.id===x)?.group!==group),id])
 return <main className="tycoon">
  <header className="masthead"><div className="brand"><span className="mark">R</span><div><h1>RADIANT <i>INDUSTRIES</i></h1><p>PRODUCT PORTFOLIO OFFICE · {game.year} Q{game.quarter}</p></div></div><div className="board-chip">BOARD CONFIDENCE <b>{game.board}</b></div><button className="advance" onClick={()=>apply(advanceChannel)}>Close Quarter <span>→</span></button></header>
  <section className="ticker"><span>EXECUTIVE WIRE</span><p>{game.action}</p><strong>{game.objectives[0]}</strong></section>
  <nav>{(['desk','markets','design','portfolio','finance','research'] as Tab[]).map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'active':''}>{x}</button>)}</nav>
  <section className="metrics"><Metric name="Treasury" value={cash(game.cash)} alert={game.cash<30}/><Metric name="Dealer receivables" value={cash(receivables)}/><Metric name="Quarterly profit" value={cash(game.ledger.profit)} alert={game.ledger.profit<0}/><Metric name="Market share" value={`${game.marketShare}%`}/></section>
  {activeEvents(game).length>0&&<section className="competition-strip"><b>COMPETITIVE LANDSCAPE</b><span>{activeEvents(game).map(e=>e.title).join(' · ')}</span><span>{rivals.map(r=>r.name).join(' · ')}</span>{game.year>=1953&&game.year<=1956&&!game.events.includes('color')&&<button onClick={()=>apply(fundStandard)}>Fund color standard · $25k</button>}</section>}
  {tab==='desk'&&<div className="desk-grid"><section className="panel chairman"><p className="eyebrow">CHAIRMAN'S DESK</p><h2>An industry is<br/><i>an argument.</i></h2><p>Build the products customers choose, price them with discipline, and turn dealer relationships into a national electronics concern.</p><div className="board-objectives"><b>BOARD MANDATE</b>{game.objectives.map(x=><span key={x}>◆ {x}</span>)}</div></section><section className="panel report"><p className="eyebrow">LAST QUARTER · P&L</p>{[['Dealer invoices',game.ledger.revenue],['Cost of goods',-game.ledger.cogs],['Marketing',-game.ledger.marketing],['Interest',-game.ledger.interest],['Net income',game.ledger.profit]].map(([n,v])=><div key={String(n)}><span>{n}</span><b className={Number(v)<0?'negative':''}>{cash(Number(v))}</b></div>)}</section><section className="panel dispatch"><p className="eyebrow">BOARD DISPATCHES</p>{game.notices.slice(0,4).map((n,i)=><article key={i} className={n.tone}><b>{n.title}</b><p>{n.body}</p></article>)}</section><section className="panel factories"><p className="eyebrow">PORTFOLIO PULSE</p>{game.programs.length?game.programs.map(p=><div key={p.id}><b>{p.name}</b><span>{p.unitsSold} sold · {cash(p.contribution)} contribution</span></div>):<div><b>No active products</b><span>Commission your first program from the design bench.</span></div>}</section></div>}
  {tab==='markets'&&<section className="panel page"><div className="section-title"><div><p className="eyebrow">NATIONAL MARKET INTELLIGENCE</p><h2>Follow the <i>customer.</i></h2></div><p className="muted">Regional conditions shape demand and freight, without requiring offices or factories.</p></div><div className="region-map">{regions.map(r=><article className="regional" key={r.id}><span>MARKET</span><h3>{r.id}</h3><p>Demand {Math.round(r.demand*100)} · Retail {Math.round(r.retail*100)}</p><small>Income {Math.round(r.income*100)} · Freight {Math.round(r.freight*100)}</small></article>)}</div></section>}
  {tab==='design'&&<section className="panel page"><div className="section-title"><div><p className="eyebrow">ENGINEERING BENCH</p><h2>Design the <i>margin.</i></h2></div><p className="muted">Products sell nationwide automatically; dealers collect on the selected payment term.</p></div><div className="design-grid"><section className="program-form"><label>Program name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Customer segment<select value={segment} onChange={e=>setSegment(e.target.value as Segment)}>{segments.map(x=><option key={x}>{x}</option>)}</select></label><label>MSRP<input type="number" min="20" value={price} onChange={e=>setPrice(Number(e.target.value))}/></label><label>Dealer discount (%)<input type="number" min="20" max="45" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label><div className="design-stats"><span>Bill of materials <b>${stats.cost}</b></span><span>Wholesale net <b>${(price*(1-discount/100)).toFixed(0)}</b></span><span>Break-even MSRP <b>${breakEven}</b></span><span>Reliability <b>{stats.reliability}%</b></span></div>{price<breakEven&&<p className="pricing-warning">Below break-even: this program is unlikely to cover itself.</p>}<button className="primary" disabled={game.cash<20} onClick={()=>apply(g=>addCommercialProgram(g,name,segment,price,discount/100,parts))}>Approve program · $20k launch</button></section><section className="component-rack">{(['platform','signal','finish','feature'] as const).map(group=><div className="component-group" key={group}><h3>{group}</h3>{available.filter(c=>c.group===group).map(c=><button key={c.id} className={parts.includes(c.id)?'selected':''} onClick={()=>toggle(c.id,c.group)}><b>{c.name}</b><small>${c.cost} BOM · +{c.appeal} appeal · {c.reliability}% reliable</small></button>)}</div>)}</section></div></section>}
  {tab==='portfolio'&&<section className="panel page"><div className="section-title"><div><p className="eyebrow">NATIONAL PRODUCT PORTFOLIO</p><h2>Manage the <i>line.</i></h2></div><p className="muted">A product’s price, shelf terms, and marketing determine its contribution.</p></div><section className="programs">{game.programs.length?game.programs.map(p=>{const u=unitEconomics(game,p);return <article key={p.id}><div><b>{p.name}</b><small>{p.segment} · {p.unitsSold} sold · ${u.margin.toFixed(0)} unit contribution · collects in {p.terms} days</small></div><label>MSRP<input type="number" value={p.price} onChange={e=>apply(g=>alterCommercialProgram(g,p.id,'price',Number(e.target.value)))}/></label><label>Dealer %<input type="number" min="20" max="45" value={Math.round(p.dealerDiscount*100)} onChange={e=>apply(g=>alterCommercialProgram(g,p.id,'dealerDiscount',Number(e.target.value)/100))}/></label><label>Marketing<input type="number" value={p.marketing} onChange={e=>apply(g=>alterCommercialProgram(g,p.id,'marketing',Number(e.target.value)))}/></label><label>Terms<select value={p.terms} onChange={e=>apply(g=>alterCommercialProgram(g,p.id,'terms',Number(e.target.value)))}><option value={30}>30d</option><option value={60}>60d</option><option value={90}>90d</option></select></label><strong>{cash(p.revenue)}</strong></article>}):<div className="empty">No product programs yet.<br/>Create one from the engineering bench.</div>}</section></section>}
  {tab==='finance'&&<section className="panel page"><div className="section-title"><div><p className="eyebrow">TREASURER'S OFFICE</p><h2>Capital has a <i>cost.</i></h2></div><p className="muted">Profit recognizes sales; cash arrives when dealer invoices mature.</p></div><div className="finance-grid"><section className="ledger"><h3>Cash flow</h3>{[['Cash collections',game.ledger.cashFlow],['Dealer invoices',game.ledger.revenue],['COGS',-game.ledger.cogs],['Marketing',-game.ledger.marketing],['Overhead',-game.ledger.overhead],['Tax',-game.ledger.tax]].map(([n,v])=><div key={String(n)}><span>{n}</span><b className={Number(v)<0?'negative':''}>{cash(Number(v))}</b></div>)}</section><section className="capital"><h3>Capital market</h3><p>Loans bridge dealer credit. Equity funds growth but reduces board confidence.</p><button onClick={()=>apply(issueLoan)}>Issue bank loan <small>+$100k · 2.5% / qtr</small></button><button onClick={()=>apply(issueEquity)}>Raise equity <small>+$120k · board −5</small></button><div className="debt-list">Receivables due: {cash(receivables)}{game.loans.map(l=><span key={l.id}>Bank note: {cash(l.principal)} · {l.rate*100}% quarterly</span>)}</div></section></div></section>}
  {tab==='research'&&<section className="panel page"><div className="section-title"><div><p className="eyebrow">CORPORATE RESEARCH BUREAU</p><h2>Patent the <i>future.</i></h2></div><div className="rp">AVAILABLE <b>{game.research} RP</b></div></div><div className="research-filter">{(['All','Consumer radio','Audio & media','Television','Components','Manufacturing','Broadcast'] as const).map(x=><button key={x} className={branch===x?'active':''} onClick={()=>setBranch(x)}>{x}</button>)}</div><div className="research-grid">{researches.filter(r=>branch==='All'||r.branch===branch).map(r=>{const status=researchStatus(game,r);return <button className={`research-card ${game.techs.includes(r.id)?'done':''} ${canResearch(game,r)?'available':''}`} key={r.id} disabled={!canResearch(game,r)} onClick={()=>apply(g=>research(g,r.id))}><span>{game.techs.includes(r.id)?'✓':r.cost}</span><em>{r.year}</em><b>{r.name}</b><p>{r.description}</p><small className="branch">{r.branch} · {researchEffectText(r)}</small><i>{game.techs.includes(r.id)?'Completed':status}</i></button>})}</div></section>}
 </main>
}
